# Generated by Django 6.0.2 on 2026-03-07 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='name',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='title',
            field=models.CharField(default='Eski Hedef', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
