# Generated by Django 6.0.2 on 2026-03-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_subscription_categorybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='auto_pay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
